title: Purely Joyful
description: >
  The writings of this blog records my journey into a purely joyful way of being, that does not waver 
  regardless of what happens in my life. I would like to share some insights that has allowed me to be 
  spontaneous and playful with whatever that life throws at me.

author: Yong
email: alcaloke@gmail.com

baseurl:
url: https://www.purelyjoyful.org

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate-v2

# header_pages:
#   - about.md

show_excerpts: true

pagination:
  enabled: true
  per_page: 5
  permalink: '/home/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

date_format: '%b %-d, %Y'

social_links:
  rss: rss

disqus:
  shortname: purelyjoyful

google_analytics: UA-142892802-2
