title: Purely Joyful
description: >
  The writings of this blog records my journey into a purely joyful way of being, that does not waver
  regardless of what happens in my life. I would like to share some insights that may help you to be
  more spontaneous and playful with whatever life throws at you.   
 
author: Yong
email: alcaloke@gmail.com

baseurl: 
url: www.purelyjoyful.org

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

show_excerpts: true

date_format: "%b %-d, %Y"

social_links:
  rss: rss

disqus:
  shortname: purelyjoyful

google_analytics: UA-142892802-2