backend:
  name: github
  repo: alcaloke/purelyjoyful.org

media_folder: 'images/uploads'

collections:
  - name: 'website-settings'
    label: 'website-settings'
    files:
      - label: 'website-settings'
        name: 'site'
        file: '_data/site.yml'
        fields:
          - label: 'Tel'
            name: 'tel'
            widget: 'string'
          - label: 'Tel display'
            name: 'tel_display'
            widget: 'string'

  - label: 'pages'
    name: 'pages'
    files:
      - label: 'Footer'
        name: 'footer'
        file: '_data/footer.yml'
        fields:
          - label: 'address'
            name: 'address'
            widget: 'object'
            fields:
              - label: 'address line 1'
                name: 'addressline1'
                widget: 'string'
              - label: 'address line 2'
                name: 'addressline2'
                widget: 'string'
              - label: 'City'
                name: 'city'
                widget: 'string'
              - label: 'Post Code'
                name: 'postcode'
                widget: 'string'
              - label: 'Image'
                name: 'image'
                widget: 'image'
