backend:
  name: github
  repo: alcaloke/purelyjoyful.org

media_folder: 'images/uploads'

collections:
  - name: 'website-settings'
    label: 'website-settings'
    files:
      - label: 'website-settings'
        name: 'site'
        file: '_data/site.yml'
        fields:
          - label: 'Tel'
            name: 'tel'
            widget: 'string'
          - label: 'Tel display'
            name: 'tel_display'
            widget: 'string'
